### ISSUE TITLE
Error is raised when I run UI after ban a function 

### ISSUE THREAD

**Issue by CaulesGe** [CSC207-UofT/course-project-sout-this_is_our_teamname#111]
![image](https://user-images.githubusercontent.com/74894206/144299563-e80b7898-e100-4e4b-ae61-3954c97282e4.png)

Seems something wrong with the removeFromBanned method in DatabaseController

**Comment by matthewrhdu** [comment]
I'm on it!

**Comment by matthewrhdu** [comment]
Fixed
